@DOC_TITLE@
Xmega Application Note
dma_example.c File Reference
XMEGA DMA driver example source.
#include "dma_driver.h"
#include "avr_compiler.h"
Defines
#define MEM_BLOCK (MEM_BLOCK_SIZE * MEM_BLOCK_COUNT)
#define MEM_BLOCK_COUNT (10)
#define MEM_BLOCK_SIZE (10)
Functions
bool BlockMemCopy (const void *src, void *dest, uint16_t blockSize, volatile DMA_CH_t *dmaChannel)
Example demonstrating block memory copy.
ISR (DMA_CH0_vect)
void main (void)
Example code using two different methods of transfer.
bool MultiBlockMemCopy (const void *src, void *dest, uint16_t blockSize, uint8_t repeatCount, volatile DMA_CH_t *dmaChannel)
Example of a repeated block memory copy operation.
Variables
volatile bool gInterruptDone
volatile bool gStatus
uint8_t memoryBlockA [MEM_BLOCK]
uint8_t memoryBlockB [MEM_BLOCK]
Detailed Description
XMEGA DMA driver example source.
This file contains an example application that demonstrates the DMA driver. It shows how to set up the DMA for a memory-to-memory block copy operation. Two functions are provided, one using single block transfer and one using repeated block transfer. Single block transfers supports up to 64k bytes, while repeated blocks supports up to 255 blocks (16M - 64k bytes). Both functions are tested in the main() function.
Application note:
AVR1304: Using the XMEGA DMA Controller
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
1569
Date
2008-04-22 13:03:43 +0200 (ti, 22 apr 2008)
Copyright (c) 2008, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file dma_example.c.
Define Documentation
#define MEM_BLOCK (MEM_BLOCK_SIZE * MEM_BLOCK_COUNT)
Total block size. Note that MEM_BLOCK_SIZE * MEM_BLOCK_COUNT must not exceed 64k for this demo application.
Definition at line 66 of file dma_example.c.
Referenced by main().
#define MEM_BLOCK_COUNT (10)
Memory block count.
Definition at line 61 of file dma_example.c.
Referenced by main().
#define MEM_BLOCK_SIZE (10)
Size of one memory block.
Definition at line 58 of file dma_example.c.
Referenced by main().
Function Documentation
bool BlockMemCopy (const void * src, void * dest, uint16_t blockSize, volatile DMA_CH_t * dmaChannel)
Example demonstrating block memory copy.
Block size 0 = 64k. Enable the DMA channel to use first and it will be disabled automatically. Setup channel for copying data, increasing addresses, no address pointer reload, with 8-byte bursts.
Note:
This function DO NOT wait for a completion, and this must be handled by the program calling this function. In this example, an interrupt.
Return values:
true if success.
false if failure.
Definition at line 88 of file dma_example.c.
References DMA_EnableChannel(), DMA_SetupBlock(), and DMA_StartTransfer().
Referenced by main().
{
        DMA_EnableChannel( dmaChannel );
        DMA_SetupBlock( dmaChannel,
                        src,
                        DMA_CH_SRCRELOAD_NONE_gc,
                        DMA_CH_SRCDIR_INC_gc,
                        dest,
                        DMA_CH_DESTRELOAD_NONE_gc,
                        DMA_CH_DESTDIR_INC_gc,
                        blockSize,
                        DMA_CH_BURSTLEN_8BYTE_gc,
                        0,
                        false );
        DMA_StartTransfer( dmaChannel );
        return true;
}
ISR (DMA_CH0_vect)
DMA CH0 Interrupt service routine. Clear interrupt flags after check.
Definition at line 262 of file dma_example.c.
References gInterruptDone, and gStatus.
{
        if (DMA.CH0.CTRLB & DMA_CH_ERRIF_bm) {
                DMA.CH0.CTRLB |= DMA_CH_ERRIF_bm;
                gStatus = false;
        } else {
                DMA.CH0.CTRLB |= DMA_CH_TRNIF_bm;
                gStatus = true;
        }
        gInterruptDone = true;
}
void main (void)
Example code using two different methods of transfer.
Example code using the two example functions to do a singe block memory copy and a multi block memory copy. The first test use a polling function to wait until the transfer completes or get an error. The second test use an interrupt to know when the transfer completes or get an error.
Definition at line 172 of file dma_example.c.
References BlockMemCopy(), DMA_Enable, DMA_SetIntLevel(), gInterruptDone, gStatus, MEM_BLOCK, MEM_BLOCK_COUNT, MEM_BLOCK_SIZE, memoryBlockA, memoryBlockB, and MultiBlockMemCopy().
{
        uint32_t index;
        volatile DMA_CH_t * Channel;
        Channel = &DMA.CH0;
        DMA_Enable();
        /* Test 1: Copy using repeated blocks. */
        /* Fill memory block A with example data. */
        for ( index = 0; index < MEM_BLOCK; ++index ) {
                memoryBlockA[index] = ( (uint8_t) index & 0xff );
        }
        /* Copy data using channel 0. */
        gStatus = MultiBlockMemCopy( memoryBlockA,
                                     memoryBlockB,
                                     MEM_BLOCK_SIZE,
                                     MEM_BLOCK_COUNT,
                                     Channel );
        /* Compare memory blocks if status is true. */
        if ( gStatus ) {
                for ( index = 0; index < MEM_BLOCK; ++index) {
                        if (memoryBlockA[index] != memoryBlockB[index]) {
                                gStatus = false;
                                break;
                        }
                }
        }
        /*  Test 2: Copy using single block mode and use interrupt. Perform
         *  second test only if first test succeeded.
         */
        if ( gStatus ) {
                /*  Enable LO interrupt level for the complete transaction and
                 *  error flag on DMA channel 0.
                 */
                DMA_SetIntLevel( Channel, DMA_CH_TRNINTLVL_LO_gc, DMA_CH_ERRINTLVL_LO_gc );
                PMIC.CTRL |= PMIC_LOLVLEN_bm;
                sei();
                /* Fill memory block A with example data again. */
                for ( index = 0; index < MEM_BLOCK; ++index ) {
                        memoryBlockA[index] = 0xff - ( (uint8_t) index & 0xff );
                }
                /* Set intDone to false to know when it has been executed. */
                gInterruptDone = false;
                /* Copy data using channel 0. */
                gStatus = BlockMemCopy( memoryBlockA,
                                        memoryBlockB,
                                        MEM_BLOCK,
                                        Channel);
                do {
                        /* Do something here while waiting for the
                         * interrupt routine to signal completion.
                         */
                } while ( gInterruptDone == false );
                /* Compare memory blocks. */
                if ( gStatus ) {
                        for ( index = 0; index < MEM_BLOCK; ++index ) {
                                if (memoryBlockA[index] != memoryBlockB[index]) {
                                        gStatus = false;
                                        break;
                                }
                        }
                }
        }
        if ( gStatus ) {
                do {
                        /* Completed with success. */
                } while (1);
        } else {
                do {
                        /* Completed with failure. */
                } while (1);
        }
}
bool MultiBlockMemCopy (const void * src, void * dest, uint16_t blockSize, uint8_t repeatCount, volatile DMA_CH_t * dmaChannel)
Example of a repeated block memory copy operation.
Block size 0 = 64k. Enable the DMA channel to use first and the channel will be disabled automatically. A parameter check to avoid illegal values. Setup channel for copying data, increasing addresses, no address pointer reload, with 8-byte bursts.
Note:
This function wait until the transfer is complete and use a blocking function which also makes this function blocking, hence the function will dead-lock if the completion or error flag never get set.
Return values:
true if success.
false if failure.
Definition at line 128 of file dma_example.c.
References DMA_EnableChannel(), DMA_ReturnStatus_non_blocking(), DMA_SetupBlock(), and DMA_StartTransfer().
Referenced by main().
{
        uint8_t flags;
        DMA_EnableChannel( dmaChannel );
        DMA_SetupBlock( dmaChannel,
                        src,
                        DMA_CH_SRCRELOAD_NONE_gc,
                        DMA_CH_SRCDIR_INC_gc,
                        dest,
                        DMA_CH_DESTRELOAD_NONE_gc,
                        DMA_CH_DESTDIR_INC_gc,
                        blockSize,
                        DMA_CH_BURSTLEN_8BYTE_gc,
                        repeatCount,
                        true );
        DMA_StartTransfer( dmaChannel );
        /* Wait until the completion or error flag is set. The flags
         * must be cleared manually.
         */
        do {
                flags = DMA_ReturnStatus_non_blocking( dmaChannel );
        } while ( flags == 0);
        dmaChannel->CTRLB |= ( flags );
        /* Check if error flag is set. */
        if ( ( flags & DMA_CH_ERRIF_bm ) != 0x00 ) {
                return false;
        } else {
                return true;
        }
}
Variable Documentation
volatile bool gInterruptDone
Global declared status for interrupt routine.
Definition at line 73 of file dma_example.c.
Referenced by ISR(), and main().
volatile bool gStatus
Definition at line 74 of file dma_example.c.
Referenced by ISR(), and main().
uint8_t memoryBlockA[MEM_BLOCK]
Memory blocks A and B for testing.
Definition at line 69 of file dma_example.c.
Referenced by main().
uint8_t memoryBlockB[MEM_BLOCK]
Definition at line 70 of file dma_example.c.
Referenced by main().